name: Checks
on:
  push:
    branches:
      - main
  pull_request: {}
  workflow_dispatch: {}
jobs:
  checks:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: 3.11
      - uses: pre-commit/action@v3.0.1
