name: Tests
on:
  push:
    branches:
      - main
  pull_request: {}
  workflow_dispatch: {}
jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11', '3.12']

    steps:
      - uses: actions/checkout@v4
      - name: Setup Python${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - uses: astral-sh/setup-uv@v7
      - name: Install
        run: |
          uv sync --frozen --group test
      - name: Run Test
        run: uv run pytest tests
