# Run tests on Windows.
# Currently, Python3.11 is only used as an environment.
# This is mainly for the sake of speed.
name: Windows tests
on:
  push:
    branches:
      - main
  pull_request: {}
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  tests:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Setup uv
        uses: astral-sh/setup-uv@c18668ad3cf93ea998bef934396af7bb5c839dc7 # v10.2.0
        with:
          python-version: 3.11
      - name: Install
        run: |
          uv sync --group test
      - name: Run Test
        run: uv run pytest tests
